// console.log('09')
// console.log('Добро ' + 'пожаловать ' + 'на курс ' + 'Алексей')
// let data = new Date()
// alert(data)
let element = document.getElementById('one')
element.id = 'Hello World'
console.log(typeof undefined)
console.log(typeof 'строка')
console.log(typeof 95)
console.log(typeof 95n)
console.log(typeof false)
console.log(typeof null)
console.log(typeof Symbol())
console.log(typeof Math)
console.log(typeof alert)